#!/usr/bin/env bash
#
# make_dist.sh — stage the make-built GXF artifacts into the official
# gxf-install/{bin,include,lib} layout (the same file organization as the
# released tarballs, e.g. gxf_5.1.0_20251114_0652b7b15_holoscan-sdk-cu12_x86_64.tar.gz)
# and pack it into dist/gxf_<ver>_<date>_<gitsha>_x86_64.tar.gz.
#
# Invoked by `make dist` (which passes all required variables; see the
# Makefile). Everything staged here comes from THIS repository:
#   include/  <- com_nvidia_gxf/common/*.hpp + com_nvidia_gxf/gxf/<module>/**.{h,hpp}
#   lib/      <- com_nvidia_gxf/bin-make/**.so (+ libtest_components.a)
#   bin/gxe   <- relinked with rpath $ORIGIN/../lib/gxf/core (dist layout)
#   lib/cmake <- generated from com_nvidia_gxf/cmake/*.in templates
#
# Modules whose libraries are NOT built by the Makefile (app/ucx/rmm/stream/
# benchmark/cli) are intentionally not distributed.

set -euo pipefail

: "${GXF_ROOT:?}" "${WS:?}" "${BUILD:?}" "${OBJ:?}" "${GXF_DEPS_PREFIX:?}"
: "${CXX:?}" "${AR:?}" "${EXT_SOS:?}" "${PYBINDS:?}" "${COMMON_LO:?}" "${LOGGER_LO:?}"
: "${YAML_CPP_A:?}" "${GFLAGS_A:?}" "${BREAKPAD_A:?}" "${LDFLAGS:?}" "${SYS_LIBS:?}"

_info() { echo -e "\e[32m[dist]\e[0m $*"; }
_err()  { echo -e "\e[31m[dist ERROR]\e[0m $*" >&2; exit 1; }

# Version strategy: the source tree honestly keeps kGxfCoreVersion "4.1.0"
# (this branch is GXF 4.1 + a 5.7.1 compatibility layer), but the PACKAGE
# version claims 5.7.1 so that downstream consumers with a versioned
# find_package (e.g. holoscan-sdk v4.5.0 requires `find_package(GXF 5.7.1
# CONFIG REQUIRED)`) accept the tarball. Only the tarball file name and
# lib/cmake/GXF/GXFConfigVersion.cmake are affected. Override with
# GXF_DIST_VERSION=<ver> if needed.
SRC_VER="$(grep -oP 'kGxfCoreVersion "\K[^"]+' "$WS/gxf/core/gxf.h")"
[[ -n "$SRC_VER" ]] || _err "cannot read kGxfCoreVersion from gxf/core/gxf.h"
VER="${GXF_DIST_VERSION:-5.7.1}"
if [[ "$VER" != "$SRC_VER" ]]; then
  _info "Source version: $SRC_VER; package version (GXF_DIST_VERSION): $VER"
fi

STAGE="$BUILD/dist/gxf-install"
rm -rf "$STAGE"
mkdir -p "$STAGE/bin" "$STAGE/include/common" "$STAGE/include/gxf" \
         "$STAGE/lib/gxf" "$STAGE/lib/cmake/GXF"

# ---------------------------------------------------------------------------
# 1. include/ — public headers from this repository
# ---------------------------------------------------------------------------
_info "Staging headers ..."
cp "$WS"/common/*.hpp "$STAGE/include/common/"

# copy_headers <module-dir-under-gxf> : all .h/.hpp, preserving subdirs,
# skipping tests/ (internal). bindings/ contain only .cpp, nothing to copy.
copy_headers() {
  local mod="$1" f
  (cd "$WS/gxf/$mod" && find . -type d -name tests -prune -o \
       -type f \( -name '*.hpp' -o -name '*.h' \) -print) |
  while read -r f; do
    mkdir -p "$STAGE/include/gxf/$mod/$(dirname "$f")"
    cp "$WS/gxf/$mod/$f" "$STAGE/include/gxf/$mod/$f"
  done
}

# modules whose libraries are built by the Makefile (+ core/std public API)
for m in behavior_tree core cuda logger multimedia network npp python_codelet \
         sample serialization std ipc/grpc ipc/http pubsub ucx; do
  copy_headers "$m"
done
# test module: only the public component/extension headers
for m in test/components test/extensions; do
  copy_headers "$m"
done

# ---------------------------------------------------------------------------
# 2. lib/ — extension .so + pybind modules built by make (+ test static lib)
# ---------------------------------------------------------------------------
_info "Staging libraries ..."
for a in $EXT_SOS $PYBINDS; do
  rel="${a#"$BUILD"/}"                       # e.g. gxf/core/libgxf_core.so
  mkdir -p "$STAGE/lib/$(dirname "$rel")"
  cp "$a" "$STAGE/lib/$rel"
done
# static test-components archive (same as the official lib/gxf/test/components/)
mkdir -p "$STAGE/lib/gxf/test/components"
"$AR" rcsD "$STAGE/lib/gxf/test/components/libtest_components.a" \
  "$OBJ"/gxf/test/components/*.o

# ---------------------------------------------------------------------------
# 3. bin/gxe — relinked for the dist layout (rpath $ORIGIN/../lib/gxf/core)
# ---------------------------------------------------------------------------
_info "Relinking gxe for the dist layout ..."
"$CXX" -o "$STAGE/bin/gxe" "$OBJ/gxf/gxe/gxe.o" \
  -Wl,--whole-archive $COMMON_LO $LOGGER_LO -Wl,--no-whole-archive \
  "$YAML_CPP_A" "$GFLAGS_A" -L"$STAGE/lib/gxf/core" -lgxf_core "$BREAKPAD_A" \
  -Wl,-rpath,'$ORIGIN/../lib/gxf/core' -lpthread $LDFLAGS $SYS_LIBS

# bin/manifest.yaml — same extension set as the Makefile's manifest target,
# with lib/gxf/... paths (relative to the gxf-install root, like the official)
_info "Writing bin/manifest.yaml ..."
{
  echo "# GXF extension manifest for the gxf-install layout (generated by make dist)"
  echo "extensions:"
  for e in gxf/std/libgxf_std.so gxf/sample/libgxf_sample.so \
      gxf/cuda/libgxf_cuda.so gxf/cuda/tests/libgxf_test_cuda.so \
      gxf/npp/libgxf_npp.so gxf/serialization/libgxf_serialization.so \
      gxf/network/libgxf_network.so gxf/multimedia/libgxf_multimedia.so \
      gxf/test/extensions/libgxf_test.so gxf/behavior_tree/libgxf_behavior_tree.so \
      gxf/ucx/libgxf_ucx.so gxf/pubsub/libgxf_pubsub.so; do
    echo "- lib/$e"
  done
} > "$STAGE/bin/manifest.yaml"

# ---------------------------------------------------------------------------
# 4. lib/cmake/GXF/ — find_package(GXF) support
# ---------------------------------------------------------------------------
_info "Generating lib/cmake/GXF ..."

# 4a. GXFConfig.cmake: expand the repo's own template (@PACKAGE_INIT@,
#     @GXF_COMPONENTS@) exactly like configure_package_config_file() does
GXF_COMPONENTS="core;logger;std;behavior_tree;cuda;test_cuda;multimedia;network;npp;serialization;sample;test_components;test_extension;grpc_ext;http;python_codelet;ucx;pubsub;gxe"
awk -v comp="$GXF_COMPONENTS" '
  /^@PACKAGE_INIT@$/ {
    print "get_filename_component(PACKAGE_PREFIX_DIR \"${CMAKE_CURRENT_LIST_DIR}/../../../\" ABSOLUTE)"
    print ""
    print "macro(set_and_check _var _file)"
    print "  set(${_var} \"${_file}\")"
    print "  if(NOT EXISTS \"${_file}\")"
    print "    message(FATAL_ERROR \"File or directory ${_file} referenced by variable ${_var} does not exist !\")"
    print "  endif()"
    print "endmacro()"
    print ""
    print "macro(check_required_components _NAME)"
    print "  foreach(comp ${${_NAME}_FIND_COMPONENTS})"
    print "    if(NOT ${_NAME}_${comp}_FOUND)"
    print "      if(${_NAME}_FIND_REQUIRED_${comp})"
    print "        set(${_NAME}_FOUND FALSE)"
    print "      endif()"
    print "    endif()"
    print "  endforeach()"
    print "endmacro()"
    next
  }
  /^set\(_GXF_components @GXF_COMPONENTS@\)$/ {
    print "set(_GXF_components " comp ")"
    next
  }
  { print }
' "$WS/cmake/GXFConfig.cmake.in" > "$STAGE/lib/cmake/GXF/GXFConfig.cmake"

# 4b. GXFConfigVersion.cmake: standard write_basic_package_version_file output
_ver_script="$BUILD/dist/ver_gen.cmake"
echo "include(CMakePackageConfigHelpers)
write_basic_package_version_file(\"$STAGE/lib/cmake/GXF/GXFConfigVersion.cmake\"
  VERSION $VER COMPATIBILITY SameMajorVersion)" > "$_ver_script"
cmake -P "$_ver_script"

# 4c. GXFCoreTargets.cmake (+ -release): core/logger/std/gxe imported targets
#     (same target set as the official package; include paths are relative to
#     the install prefix)
cat > "$STAGE/lib/cmake/GXF/GXFCoreTargets.cmake" <<'EOF_CORE'
# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 3.0.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "3.0.0")
   message(FATAL_ERROR "CMake >= 3.0.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 3.0.0...3.29)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS GXF::common GXF::common_internal GXF::core_c_api GXF::core_internal GXF::core GXF::logger GXF::gxf_logger GXF::std_gems_event_list_event_list GXF::std_gems_event_list_unique_event_list GXF::std_gems_event_list GXF::std_gems_pool_fixed_pool_uint64 GXF::std_gems_queue_thread GXF::std_gems_staging_queue_staging_queue GXF::std_gems_staging_queue_staging_queue_iterator GXF::std_gems_staging_queue GXF::std_gems_suballocators_internal GXF::std_gems_timed_job_list GXF::std_gems_utils_internal GXF::std_gems_video_buffer GXF::std_internal GXF::std GXF::gxe)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target GXF::common
add_library(GXF::common INTERFACE IMPORTED)

set_target_properties(GXF::common PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "GXF::common_internal;GXF::logger;\$<LINK_ONLY:Threads::Threads>"
)

# Create imported target GXF::common_internal
add_library(GXF::common_internal INTERFACE IMPORTED)

set_target_properties(GXF::common_internal PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "CUDA::nvtx3"
)

# Create imported target GXF::core_c_api
add_library(GXF::core_c_api INTERFACE IMPORTED)

# Create imported target GXF::core_internal
add_library(GXF::core_internal INTERFACE IMPORTED)

set_target_properties(GXF::core_internal PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "GXF::common;GXF::core_c_api;GXF::logger;Threads::Threads;magic_enum::magic_enum;\$<LINK_ONLY:yaml-cpp>"
)

# Create imported target GXF::core
add_library(GXF::core SHARED IMPORTED)

set_target_properties(GXF::core PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "GXF::common;GXF::core_internal;GXF::logger;Threads::Threads"
)

# Create imported target GXF::logger
add_library(GXF::logger SHARED IMPORTED)

set_target_properties(GXF::logger PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target GXF::gxf_logger
add_library(GXF::gxf_logger INTERFACE IMPORTED)

set_target_properties(GXF::gxf_logger PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "GXF::logger"
)

# Create imported target GXF::std_gems_event_list_event_list
add_library(GXF::std_gems_event_list_event_list INTERFACE IMPORTED)

set_target_properties(GXF::std_gems_event_list_event_list PROPERTIES
  INTERFACE_LINK_LIBRARIES "GXF::common;Threads::Threads"
)

# Create imported target GXF::std_gems_event_list_unique_event_list
add_library(GXF::std_gems_event_list_unique_event_list INTERFACE IMPORTED)

set_target_properties(GXF::std_gems_event_list_unique_event_list PROPERTIES
  INTERFACE_LINK_LIBRARIES "GXF::common;Threads::Threads"
)

# Create imported target GXF::std_gems_event_list
add_library(GXF::std_gems_event_list INTERFACE IMPORTED)

set_target_properties(GXF::std_gems_event_list PROPERTIES
  INTERFACE_LINK_LIBRARIES "GXF::std_gems_event_list_event_list;GXF::std_gems_event_list_unique_event_list"
)

# Create imported target GXF::std_gems_pool_fixed_pool_uint64
add_library(GXF::std_gems_pool_fixed_pool_uint64 INTERFACE IMPORTED)

set_target_properties(GXF::std_gems_pool_fixed_pool_uint64 PROPERTIES
  INTERFACE_LINK_LIBRARIES "GXF::common"
)

# Create imported target GXF::std_gems_queue_thread
add_library(GXF::std_gems_queue_thread INTERFACE IMPORTED)

set_target_properties(GXF::std_gems_queue_thread PROPERTIES
  INTERFACE_LINK_LIBRARIES "GXF::core_internal"
)

# Create imported target GXF::std_gems_staging_queue_staging_queue
add_library(GXF::std_gems_staging_queue_staging_queue INTERFACE IMPORTED)

set_target_properties(GXF::std_gems_staging_queue_staging_queue PROPERTIES
  INTERFACE_LINK_LIBRARIES "GXF::std_gems_staging_queue_staging_queue_iterator;GXF::common;Threads::Threads"
)

# Create imported target GXF::std_gems_staging_queue_staging_queue_iterator
add_library(GXF::std_gems_staging_queue_staging_queue_iterator INTERFACE IMPORTED)

# Create imported target GXF::std_gems_staging_queue
add_library(GXF::std_gems_staging_queue INTERFACE IMPORTED)

set_target_properties(GXF::std_gems_staging_queue PROPERTIES
  INTERFACE_LINK_LIBRARIES "GXF::std_gems_staging_queue_staging_queue;GXF::std_gems_staging_queue_staging_queue_iterator"
)

# Create imported target GXF::std_gems_suballocators_internal
add_library(GXF::std_gems_suballocators_internal INTERFACE IMPORTED)

set_target_properties(GXF::std_gems_suballocators_internal PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "GXF::common;GXF::core_internal"
)

# Create imported target GXF::std_gems_timed_job_list
add_library(GXF::std_gems_timed_job_list INTERFACE IMPORTED)

set_target_properties(GXF::std_gems_timed_job_list PROPERTIES
  INTERFACE_LINK_LIBRARIES "GXF::core_internal"
)

# Create imported target GXF::std_gems_utils_internal
add_library(GXF::std_gems_utils_internal INTERFACE IMPORTED)

set_target_properties(GXF::std_gems_utils_internal PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "GXF::common;GXF::core_internal"
)

# Create imported target GXF::std_gems_video_buffer
add_library(GXF::std_gems_video_buffer INTERFACE IMPORTED)

set_target_properties(GXF::std_gems_video_buffer PROPERTIES
  INTERFACE_LINK_LIBRARIES "GXF::core_internal"
)

# Create imported target GXF::std_internal
add_library(GXF::std_internal INTERFACE IMPORTED)

set_target_properties(GXF::std_internal PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "GXF::common;GXF::core_internal;GXF::std_gems_event_list;GXF::std_gems_pool_fixed_pool_uint64;GXF::std_gems_queue_thread;GXF::std_gems_staging_queue;GXF::std_gems_timed_job_list;GXF::std_gems_video_buffer;CCCL::CCCL;CUDA::cudart;CUDA::nvtx3;dlpack::dlpack;Threads::Threads;yaml-cpp;\$<LINK_ONLY:GXF::std_gems_suballocators_internal>;\$<LINK_ONLY:GXF::std_gems_utils_internal>"
)

# Create imported target GXF::std
add_library(GXF::std SHARED IMPORTED)

set_target_properties(GXF::std PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "GXF::common;GXF::core;GXF::std_internal;CCCL::CCCL"
)

# Create imported target GXF::gxe
add_executable(GXF::gxe IMPORTED)

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/GXFCoreTargets-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
    if(NOT EXISTS "${_cmake_file}")
      message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
EOF_CORE

cat > "$STAGE/lib/cmake/GXF/GXFCoreTargets-release.cmake" <<'EOF_COREREL'
#----------------------------------------------------------------
# Generated CMake target import file for configuration "Release".
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Import target "GXF::core" for configuration "Release"
set_property(TARGET GXF::core APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(GXF::core PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/gxf/core/libgxf_core.so"
  IMPORTED_SONAME_RELEASE "libgxf_core.so"
  )

list(APPEND _cmake_import_check_targets GXF::core )
list(APPEND _cmake_import_check_files_for_GXF::core "${_IMPORT_PREFIX}/lib/gxf/core/libgxf_core.so" )

# Import target "GXF::logger" for configuration "Release"
set_property(TARGET GXF::logger APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(GXF::logger PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/gxf/logger/libgxf_logger.so"
  IMPORTED_SONAME_RELEASE "libgxf_logger.so"
  )

list(APPEND _cmake_import_check_targets GXF::logger )
list(APPEND _cmake_import_check_files_for_GXF::logger "${_IMPORT_PREFIX}/lib/gxf/logger/libgxf_logger.so" )

# Import target "GXF::std" for configuration "Release"
set_property(TARGET GXF::std APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(GXF::std PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/gxf/std/libgxf_std.so"
  IMPORTED_SONAME_RELEASE "libgxf_std.so"
  )

list(APPEND _cmake_import_check_targets GXF::std )
list(APPEND _cmake_import_check_files_for_GXF::std "${_IMPORT_PREFIX}/lib/gxf/std/libgxf_std.so" )

# Import target "GXF::gxe" for configuration "Release"
set_property(TARGET GXF::gxe APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(GXF::gxe PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/gxe"
  )

list(APPEND _cmake_import_check_targets GXF::gxe )
list(APPEND _cmake_import_check_files_for_GXF::gxe "${_IMPORT_PREFIX}/bin/gxe" )

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
EOF_COREREL

# 4d. GXFExtensionTargets.cmake (+ -release): one imported target per shipped
#     extension library. Table: <target>|<type>|<link libs>|<relative path>
_ext_header() {
  cat <<'EOF_EXTHDR'
# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 3.0.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "3.0.0")
   message(FATAL_ERROR "CMake >= 3.0.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 3.0.0...3.29)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()
EOF_EXTHDR
}

_ext_footer() {
  cat <<'EOF_EXTFTR'
# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/GXFExtensionTargets-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
    if(NOT EXISTS "${_cmake_file}")
      message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
EOF_EXTFTR
}

EXT_TABLE=(
  "behavior_tree|SHARED|GXF::core;GXF::std|lib/gxf/behavior_tree/libgxf_behavior_tree.so"
  "cuda|SHARED|GXF::common;GXF::core;GXF::std;CUDA::cudart|lib/gxf/cuda/libgxf_cuda.so"
  "test_cuda|SHARED|GXF::cuda;GXF::std;CUDA::cudart|lib/gxf/cuda/tests/libgxf_test_cuda.so"
  "multimedia|SHARED|GXF::core;GXF::std|lib/gxf/multimedia/libgxf_multimedia.so"
  "network|SHARED|GXF::core;GXF::std|lib/gxf/network/libgxf_network.so"
  "npp|SHARED|GXF::core;GXF::std;CUDA::cudart|lib/gxf/npp/libgxf_npp.so"
  "sample|SHARED|GXF::core;GXF::std|lib/gxf/sample/libgxf_sample.so"
  "serialization|SHARED|GXF::core;GXF::std;CUDA::cudart|lib/gxf/serialization/libgxf_serialization.so"
  "test_components|STATIC|GXF::std;\$<LINK_ONLY:CUDA::cudart>|lib/gxf/test/components/libtest_components.a"
  "test_extension|SHARED|GXF::common;GXF::core;GXF::std;GXF::test_components|lib/gxf/test/extensions/libgxf_test.so"
  "grpc_ext|SHARED|GXF::core;GXF::std|lib/gxf/ipc/grpc/libgxf_grpc.so"
  "http|SHARED|GXF::core;GXF::std|lib/gxf/ipc/http/libgxf_http.so"
  "python_codelet|SHARED|GXF::core;GXF::std;CUDA::cudart|lib/gxf/python_codelet/libgxf_python_codelet.so"
  "ucx|SHARED|GXF::multimedia;GXF::serialization;GXF::std;ucx::ucp;ucx::ucs|lib/gxf/ucx/libgxf_ucx.so"
  "pubsub|SHARED|GXF::common;GXF::core;GXF::std;CUDA::cudart|lib/gxf/pubsub/libgxf_pubsub.so"
)

{
  _ext_header
  for row in "${EXT_TABLE[@]}"; do
    IFS='|' read -r name type libs loc <<< "$row"
    cat <<EOF_EXT

# Create imported target GXF::$name
add_library(GXF::$name $type IMPORTED)

set_target_properties(GXF::$name PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "\${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "$libs"
)
EOF_EXT
  done
  _ext_footer
} > "$STAGE/lib/cmake/GXF/GXFExtensionTargets.cmake"

{
  cat <<'EOF_RELHDR'
#----------------------------------------------------------------
# Generated CMake target import file for configuration "Release".
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)
EOF_RELHDR
  for row in "${EXT_TABLE[@]}"; do
    IFS='|' read -r name type libs loc <<< "$row"
    base="$(basename "$loc")"
    cat <<EOF_REL

# Import target "GXF::$name" for configuration "Release"
set_property(TARGET GXF::$name APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(GXF::$name PROPERTIES
EOF_REL
    if [[ "$type" == STATIC ]]; then
      cat <<EOF_REL
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "\${_IMPORT_PREFIX}/$loc"
EOF_REL
    else
      cat <<EOF_REL
  IMPORTED_LOCATION_RELEASE "\${_IMPORT_PREFIX}/$loc"
  IMPORTED_SONAME_RELEASE "$base"
EOF_REL
    fi
    cat <<EOF_REL
  )

list(APPEND _cmake_import_check_targets GXF::$name )
list(APPEND _cmake_import_check_files_for_GXF::$name "\${_IMPORT_PREFIX}/$loc" )
EOF_REL
  done
  echo
  echo "# Commands beyond this point should not need to know the version."
  echo "set(CMAKE_IMPORT_FILE_VERSION)"
} > "$STAGE/lib/cmake/GXF/GXFExtensionTargets-release.cmake"

# 4e. UseGXF.cmake: shipped verbatim from the repo
cp "$WS/cmake/UseGXF.cmake" "$STAGE/lib/cmake/GXF/UseGXF.cmake"

# ---------------------------------------------------------------------------
# 5. Tarball
# ---------------------------------------------------------------------------
SHA="$(git -C "$GXF_ROOT" rev-parse --short=9 HEAD 2>/dev/null || echo nogit)"
mkdir -p "$GXF_ROOT/dist"
TARBALL="$GXF_ROOT/dist/gxf_${VER}_$(date +%Y%m%d)_${SHA}_x86_64.tar.gz"
rm -f "$TARBALL"
tar -czf "$TARBALL" -C "$BUILD/dist" ./gxf-install

_info "Staged at $STAGE"
_info "  headers : $(find "$STAGE/include" -type f | wc -l) files"
_info "  libs    : $(find "$STAGE/lib/gxf" -type f | wc -l) files"
_info "Tarball : $TARBALL"
